-- AUTO-GENERATED by setup-agents-dev-supabase.mjs — paste into a DEV Supabase SQL Editor only.
-- Do NOT run on live project gpbqlxowvwosonatiuac.
-- Idempotent for DEV re-runs (DROP POLICY/TRIGGER IF EXISTS + IF NOT EXISTS on tables/indexes).
-- Numbered migration files are left unchanged for one-shot deploy; transform happens here only.
-- Generated: 2026-10-01T14:27:59.855Z


-- ========== 001_create_tables.sql ==========

-- Create profiles table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  created_at timestamp with time zone default now()
);

alter table public.profiles enable row level security;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles for select
  using (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own"
  ON public.profiles for insert
  with check (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles for update
  using (auth.uid() = id);

-- Create resume_versions table
create table if not exists public.resume_versions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  resume_text text not null,
  contact_info jsonb not null default '{}'::jsonb,
  profile_image text,
  company_logo text,
  accent_color text default '#84cc16',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.resume_versions enable row level security;

DROP POLICY IF EXISTS "resume_versions_select_own" ON public.resume_versions;
CREATE POLICY "resume_versions_select_own"
  ON public.resume_versions for select
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_insert_own" ON public.resume_versions;
CREATE POLICY "resume_versions_insert_own"
  ON public.resume_versions for insert
  with check (auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_update_own" ON public.resume_versions;
CREATE POLICY "resume_versions_update_own"
  ON public.resume_versions for update
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_delete_own" ON public.resume_versions;
CREATE POLICY "resume_versions_delete_own"
  ON public.resume_versions for delete
  using (auth.uid() = user_id);

-- Create job_applications table
create table if not exists public.job_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  company text not null,
  status text not null default 'applied',
  job_description jsonb,
  why_content jsonb,
  company_info jsonb,
  cover_letter jsonb,
  contacts jsonb,
  interview_prep jsonb,
  job_strategy jsonb,
  applied_date timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.job_applications enable row level security;

DROP POLICY IF EXISTS "job_applications_select_own" ON public.job_applications;
CREATE POLICY "job_applications_select_own"
  ON public.job_applications for select
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_insert_own" ON public.job_applications;
CREATE POLICY "job_applications_insert_own"
  ON public.job_applications for insert
  with check (auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_update_own" ON public.job_applications;
CREATE POLICY "job_applications_update_own"
  ON public.job_applications for update
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_delete_own" ON public.job_applications;
CREATE POLICY "job_applications_delete_own"
  ON public.job_applications for delete
  using (auth.uid() = user_id);


-- ========== 002_profile_trigger.sql ==========

-- Auto-create profile on user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', null)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();


-- ========== 004_create_folders.sql ==========

-- Create folders table
CREATE TABLE IF NOT EXISTS folders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add folder_id column to resume_versions
ALTER TABLE resume_versions 
ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES folders(id) ON DELETE CASCADE;

-- Add folder_id column to job_applications
ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES folders(id) ON DELETE CASCADE;

-- CREATE INDEX IF NOT EXISTS for better performance
CREATE INDEX IF NOT EXISTS idx_resume_versions_folder_id ON resume_versions(folder_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_folder_id ON job_applications(folder_id);


-- ========== 005_create_cover_letters.sql ==========

-- Create cover_letters table for standalone cover letters (not tied to job applications)
CREATE TABLE IF NOT EXISTS cover_letters (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  content_en TEXT,
  content_de TEXT,
  contact_person_name TEXT,
  folder_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);


-- ========== 006_add_user_id_and_rls.sql ==========

-- Add user_id to folders table and enable RLS
ALTER TABLE folders ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Enable RLS on folders
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;

-- Folders RLS policies
DROP POLICY IF EXISTS "Users can view their own folders" ON folders;
CREATE POLICY "Users can view their own folders" ON folders
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own folders" ON folders;
CREATE POLICY "Users can insert their own folders" ON folders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own folders" ON folders;
CREATE POLICY "Users can update their own folders" ON folders
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own folders" ON folders;
CREATE POLICY "Users can delete their own folders" ON folders
  FOR DELETE USING (auth.uid() = user_id);

-- Update resume_versions RLS (table already has user_id)
ALTER TABLE resume_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own resumes" ON resume_versions;
CREATE POLICY "Users can view their own resumes" ON resume_versions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own resumes" ON resume_versions;
CREATE POLICY "Users can insert their own resumes" ON resume_versions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own resumes" ON resume_versions;
CREATE POLICY "Users can update their own resumes" ON resume_versions
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own resumes" ON resume_versions;
CREATE POLICY "Users can delete their own resumes" ON resume_versions
  FOR DELETE USING (auth.uid() = user_id);

-- Update job_applications RLS (table already has user_id)
ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own job applications" ON job_applications;
CREATE POLICY "Users can view their own job applications" ON job_applications
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own job applications" ON job_applications;
CREATE POLICY "Users can insert their own job applications" ON job_applications
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own job applications" ON job_applications;
CREATE POLICY "Users can update their own job applications" ON job_applications
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own job applications" ON job_applications;
CREATE POLICY "Users can delete their own job applications" ON job_applications
  FOR DELETE USING (auth.uid() = user_id);

-- Add user_id to cover_letters and enable RLS
ALTER TABLE cover_letters ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE cover_letters ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own cover letters" ON cover_letters;
CREATE POLICY "Users can view their own cover letters" ON cover_letters
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own cover letters" ON cover_letters;
CREATE POLICY "Users can insert their own cover letters" ON cover_letters
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own cover letters" ON cover_letters;
CREATE POLICY "Users can update their own cover letters" ON cover_letters
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own cover letters" ON cover_letters;
CREATE POLICY "Users can delete their own cover letters" ON cover_letters
  FOR DELETE USING (auth.uid() = user_id);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_folders_user_id ON folders(user_id);
CREATE INDEX IF NOT EXISTS idx_resume_versions_user_id ON resume_versions(user_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_user_id ON job_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_cover_letters_user_id ON cover_letters(user_id);
CREATE INDEX IF NOT EXISTS idx_resume_versions_folder_id ON resume_versions(folder_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_folder_id ON job_applications(folder_id);
CREATE INDEX IF NOT EXISTS idx_cover_letters_folder_id ON cover_letters(folder_id);


-- ========== 008_add_cover_letter_id_to_jobs.sql ==========

-- Add cover_letter_id column to job_applications table
ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS cover_letter_id text;

-- Add resume_version_id column if it doesn't exist
ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS resume_version_id text;


-- ========== 009_add_fit_scores_and_red_flags.sql ==========

-- Add fit_scores and red_flags columns to job_applications table
ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS fit_scores JSONB DEFAULT '{}';

ALTER TABLE job_applications 
ADD COLUMN IF NOT EXISTS red_flags JSONB DEFAULT '[]';


-- ========== 010_add_resume_style_columns.sql ==========

alter table resume_versions
add column if not exists profile_photo_border boolean default true;

alter table resume_versions
add column if not exists target_box_bg_color text;

alter table resume_versions
add column if not exists target_box_border_color text;


-- ========== 010_add_upload_details.sql ==========

-- Application form answer drafts (salary, motivation, availability, etc.)
ALTER TABLE job_applications
ADD COLUMN IF NOT EXISTS upload_details JSONB DEFAULT NULL;


-- ========== 011_add_resume_embedded_cover_letter.sql ==========

-- Store per-resume cover letter on the resume row (scoped by resume id)
ALTER TABLE resume_versions
ADD COLUMN IF NOT EXISTS resume_cover_letter JSONB DEFAULT NULL;

COMMENT ON COLUMN resume_versions.resume_cover_letter IS 'Cover letter content belonging to this resume only';


-- ========== 012_add_resume_version_history.sql ==========

-- Resume version history: content snapshots belong to one resume record.
alter table public.resume_versions
  add column if not exists version_history jsonb default '[]'::jsonb;

alter table public.resume_versions
  add column if not exists application_id uuid;


-- ========== add-folder-contact-info.sql ==========

-- Add profile_image and contact_info columns to folders table
-- These store default contact info and profile photo for all resumes in the workspace

ALTER TABLE folders 
ADD COLUMN IF NOT EXISTS profile_image TEXT,
ADD COLUMN IF NOT EXISTS contact_info JSONB DEFAULT '{}'::jsonb;

-- Add comment for documentation
COMMENT ON COLUMN folders.profile_image IS 'Default profile image (base64) for all resumes in this folder';
COMMENT ON COLUMN folders.contact_info IS 'Default contact information for all resumes in this folder';


-- ========== 013_enable_rls_security.sql ==========

-- Enable Row Level Security for CV Tool (project gpbqlxowvwosonatiuac)
--
-- Run in Supabase Dashboard → SQL Editor AFTER creating one Supabase Auth user
-- for the app (Authentication → Users → Add user):
--   Email: value of SUPABASE_APP_USER_EMAIL in your server env
--   Password: value of SUPABASE_APP_USER_PASSWORD in your server env
--
-- The app signs into this user after your normal username/password login.
-- Anonymous API access (public anon key, no session) is blocked.

-- ---------------------------------------------------------------------------
-- Drop legacy / conflicting policies (001 + 006 naming)
-- ---------------------------------------------------------------------------

-- profiles
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;

-- folders
DROP POLICY IF EXISTS "Users can view their own folders" ON public.folders;
DROP POLICY IF EXISTS "Users can insert their own folders" ON public.folders;
DROP POLICY IF EXISTS "Users can update their own folders" ON public.folders;
DROP POLICY IF EXISTS "Users can delete their own folders" ON public.folders;
DROP POLICY IF EXISTS "Users can manage their own folders" ON public.folders;

-- resume_versions
DROP POLICY IF EXISTS "Users can view their own resumes" ON public.resume_versions;
DROP POLICY IF EXISTS "Users can insert their own resumes" ON public.resume_versions;
DROP POLICY IF EXISTS "Users can update their own resumes" ON public.resume_versions;
DROP POLICY IF EXISTS "Users can delete their own resumes" ON public.resume_versions;
DROP POLICY IF EXISTS "Users can manage their own resumes" ON public.resume_versions;
DROP POLICY IF EXISTS "resume_versions_select_own" ON public.resume_versions;
DROP POLICY IF EXISTS "resume_versions_insert_own" ON public.resume_versions;
DROP POLICY IF EXISTS "resume_versions_update_own" ON public.resume_versions;
DROP POLICY IF EXISTS "resume_versions_delete_own" ON public.resume_versions;

-- job_applications
DROP POLICY IF EXISTS "Users can view their own job applications" ON public.job_applications;
DROP POLICY IF EXISTS "Users can insert their own job applications" ON public.job_applications;
DROP POLICY IF EXISTS "Users can update their own job applications" ON public.job_applications;
DROP POLICY IF EXISTS "Users can delete their own job applications" ON public.job_applications;
DROP POLICY IF EXISTS "Users can manage their own applications" ON public.job_applications;
DROP POLICY IF EXISTS "job_applications_select_own" ON public.job_applications;
DROP POLICY IF EXISTS "job_applications_insert_own" ON public.job_applications;
DROP POLICY IF EXISTS "job_applications_update_own" ON public.job_applications;
DROP POLICY IF EXISTS "job_applications_delete_own" ON public.job_applications;

-- cover_letters
DROP POLICY IF EXISTS "Users can view their own cover letters" ON public.cover_letters;
DROP POLICY IF EXISTS "Users can insert their own cover letters" ON public.cover_letters;
DROP POLICY IF EXISTS "Users can update their own cover letters" ON public.cover_letters;
DROP POLICY IF EXISTS "Users can delete their own cover letters" ON public.cover_letters;
DROP POLICY IF EXISTS "Users can manage their own cover letters" ON public.cover_letters;

-- ---------------------------------------------------------------------------
-- Enable RLS (no anon policies → unauthenticated API access is denied)
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resume_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cover_letters ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Shared helper: legacy rows may have user_id NULL until backfilled
-- ---------------------------------------------------------------------------

-- profiles
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT TO authenticated
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own"
  ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- folders
DROP POLICY IF EXISTS "folders_select_authenticated" ON public.folders;
CREATE POLICY "folders_select_authenticated"
  ON public.folders FOR SELECT TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "folders_insert_authenticated" ON public.folders;
CREATE POLICY "folders_insert_authenticated"
  ON public.folders FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "folders_update_authenticated" ON public.folders;
CREATE POLICY "folders_update_authenticated"
  ON public.folders FOR UPDATE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id)
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "folders_delete_authenticated" ON public.folders;
CREATE POLICY "folders_delete_authenticated"
  ON public.folders FOR DELETE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

-- resume_versions
DROP POLICY IF EXISTS "resume_versions_select_authenticated" ON public.resume_versions;
CREATE POLICY "resume_versions_select_authenticated"
  ON public.resume_versions FOR SELECT TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_insert_authenticated" ON public.resume_versions;
CREATE POLICY "resume_versions_insert_authenticated"
  ON public.resume_versions FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_update_authenticated" ON public.resume_versions;
CREATE POLICY "resume_versions_update_authenticated"
  ON public.resume_versions FOR UPDATE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id)
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "resume_versions_delete_authenticated" ON public.resume_versions;
CREATE POLICY "resume_versions_delete_authenticated"
  ON public.resume_versions FOR DELETE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

-- job_applications
DROP POLICY IF EXISTS "job_applications_select_authenticated" ON public.job_applications;
CREATE POLICY "job_applications_select_authenticated"
  ON public.job_applications FOR SELECT TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_insert_authenticated" ON public.job_applications;
CREATE POLICY "job_applications_insert_authenticated"
  ON public.job_applications FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_update_authenticated" ON public.job_applications;
CREATE POLICY "job_applications_update_authenticated"
  ON public.job_applications FOR UPDATE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id)
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "job_applications_delete_authenticated" ON public.job_applications;
CREATE POLICY "job_applications_delete_authenticated"
  ON public.job_applications FOR DELETE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

-- cover_letters
DROP POLICY IF EXISTS "cover_letters_select_authenticated" ON public.cover_letters;
CREATE POLICY "cover_letters_select_authenticated"
  ON public.cover_letters FOR SELECT TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "cover_letters_insert_authenticated" ON public.cover_letters;
CREATE POLICY "cover_letters_insert_authenticated"
  ON public.cover_letters FOR INSERT TO authenticated
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "cover_letters_update_authenticated" ON public.cover_letters;
CREATE POLICY "cover_letters_update_authenticated"
  ON public.cover_letters FOR UPDATE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id)
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "cover_letters_delete_authenticated" ON public.cover_letters;
CREATE POLICY "cover_letters_delete_authenticated"
  ON public.cover_letters FOR DELETE TO authenticated
  USING (user_id IS NULL OR auth.uid() = user_id);

-- Optional: attach existing NULL user_id rows to your app service user
-- (uncomment and replace the UUID after creating the Supabase Auth user)
-- UPDATE folders SET user_id = 'YOUR-SUPABASE-AUTH-USER-UUID' WHERE user_id IS NULL;
-- UPDATE resume_versions SET user_id = 'YOUR-SUPABASE-AUTH-USER-UUID' WHERE user_id IS NULL;
-- UPDATE job_applications SET user_id = 'YOUR-SUPABASE-AUTH-USER-UUID' WHERE user_id IS NULL;
-- UPDATE cover_letters SET user_id = 'YOUR-SUPABASE-AUTH-USER-UUID' WHERE user_id IS NULL;

NOTIFY pgrst, 'reload schema';


-- ========== 016_add_your_story.sql ==========

-- Per-application internal positioning narrative ("Your Story")
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS your_story JSONB DEFAULT NULL;

NOTIFY pgrst, 'reload schema';


-- ========== apply-missing-supabase-schema.sql ==========

-- Run once in Supabase Dashboard → SQL Editor for project gpbqlxowvwosonatiuac
-- Fixes PGRST204 errors when the app syncs resumes to the cloud.

-- resume_versions: styling
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS profile_photo_border BOOLEAN DEFAULT true;
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS target_box_bg_color TEXT DEFAULT '#f8f9fa';
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS target_box_border_color TEXT DEFAULT '';

-- resume_versions: job description + embedded cover letter + version history
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS job_description TEXT;
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS resume_cover_letter JSONB DEFAULT NULL;
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS version_history JSONB DEFAULT '[]'::jsonb;
ALTER TABLE resume_versions ADD COLUMN IF NOT EXISTS application_id UUID;

-- job_applications: upload details draft
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS upload_details JSONB DEFAULT NULL;

-- job_applications: internal positioning narrative
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS your_story JSONB DEFAULT NULL;

-- Refresh PostgREST schema cache (usually automatic within ~1 min)
NOTIFY pgrst, 'reload schema';


-- ========== 020_agent_tables.sql ==========

-- Job agents v2 — additive schema (Phase 2)
-- Creates all six agent_* tables so later phases do not rename.
-- Run in Supabase Dashboard → SQL Editor (or apply via your usual migration path).
-- Pair: 020_agent_tables_down.sql

-- ---------------------------------------------------------------------------
-- 1. agent_profile_facts — atomic master-profile facts (confirm before use)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_profile_facts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category text NOT NULL DEFAULT 'other',
  fact_text text NOT NULL,
  status text NOT NULL DEFAULT 'unconfirmed'
    CHECK (status IN ('unconfirmed', 'confirmed')),
  source text NOT NULL DEFAULT 'manual'
    CHECK (source IN ('resume', 'qualification_profile', 'manual')),
  source_ref jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Idempotent seed key (resume/qualification imports). NULL for manual facts.
  source_key text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agent_profile_facts_text_nonempty CHECK (char_length(trim(fact_text)) > 0),
  -- NULL source_key allowed for manual facts (Postgres treats NULLs as distinct)
  CONSTRAINT agent_profile_facts_user_source_key_unique UNIQUE (user_id, source_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_profile_facts_user_id
  ON public.agent_profile_facts (user_id);

CREATE INDEX IF NOT EXISTS idx_agent_profile_facts_user_status
  ON public.agent_profile_facts (user_id, status);

ALTER TABLE public.agent_profile_facts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_profile_facts_select_authenticated" ON public.agent_profile_facts;
DROP POLICY IF EXISTS "agent_profile_facts_insert_authenticated" ON public.agent_profile_facts;
DROP POLICY IF EXISTS "agent_profile_facts_update_authenticated" ON public.agent_profile_facts;
DROP POLICY IF EXISTS "agent_profile_facts_delete_authenticated" ON public.agent_profile_facts;

DROP POLICY IF EXISTS "agent_profile_facts_select_authenticated" ON public.agent_profile_facts;
CREATE POLICY "agent_profile_facts_select_authenticated"
  ON public.agent_profile_facts FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_profile_facts_insert_authenticated" ON public.agent_profile_facts;
CREATE POLICY "agent_profile_facts_insert_authenticated"
  ON public.agent_profile_facts FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_profile_facts_update_authenticated" ON public.agent_profile_facts;
CREATE POLICY "agent_profile_facts_update_authenticated"
  ON public.agent_profile_facts FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_profile_facts_delete_authenticated" ON public.agent_profile_facts;
CREATE POLICY "agent_profile_facts_delete_authenticated"
  ON public.agent_profile_facts FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 2. agent_search_settings — per-user search preferences (UI may come later)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_search_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  keywords text[] NOT NULL DEFAULT '{}'::text[],
  location text NOT NULL DEFAULT 'Berlin',
  remote boolean NOT NULL DEFAULT false,
  languages text[] NOT NULL DEFAULT '{}'::text[],
  seniority text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agent_search_settings_user_unique UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_search_settings_user_id
  ON public.agent_search_settings (user_id);

ALTER TABLE public.agent_search_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_search_settings_select_authenticated" ON public.agent_search_settings;
DROP POLICY IF EXISTS "agent_search_settings_insert_authenticated" ON public.agent_search_settings;
DROP POLICY IF EXISTS "agent_search_settings_update_authenticated" ON public.agent_search_settings;
DROP POLICY IF EXISTS "agent_search_settings_delete_authenticated" ON public.agent_search_settings;

DROP POLICY IF EXISTS "agent_search_settings_select_authenticated" ON public.agent_search_settings;
CREATE POLICY "agent_search_settings_select_authenticated"
  ON public.agent_search_settings FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_search_settings_insert_authenticated" ON public.agent_search_settings;
CREATE POLICY "agent_search_settings_insert_authenticated"
  ON public.agent_search_settings FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_search_settings_update_authenticated" ON public.agent_search_settings;
CREATE POLICY "agent_search_settings_update_authenticated"
  ON public.agent_search_settings FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_search_settings_delete_authenticated" ON public.agent_search_settings;
CREATE POLICY "agent_search_settings_delete_authenticated"
  ON public.agent_search_settings FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 3. agent_companies — normalized companies for listings + initiative apps
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  normalized_name text,
  website text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agent_companies_name_nonempty CHECK (char_length(trim(name)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_agent_companies_user_id
  ON public.agent_companies (user_id);

CREATE INDEX IF NOT EXISTS idx_agent_companies_user_normalized
  ON public.agent_companies (user_id, normalized_name);

ALTER TABLE public.agent_companies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_companies_select_authenticated" ON public.agent_companies;
DROP POLICY IF EXISTS "agent_companies_insert_authenticated" ON public.agent_companies;
DROP POLICY IF EXISTS "agent_companies_update_authenticated" ON public.agent_companies;
DROP POLICY IF EXISTS "agent_companies_delete_authenticated" ON public.agent_companies;

DROP POLICY IF EXISTS "agent_companies_select_authenticated" ON public.agent_companies;
CREATE POLICY "agent_companies_select_authenticated"
  ON public.agent_companies FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_companies_insert_authenticated" ON public.agent_companies;
CREATE POLICY "agent_companies_insert_authenticated"
  ON public.agent_companies FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_companies_update_authenticated" ON public.agent_companies;
CREATE POLICY "agent_companies_update_authenticated"
  ON public.agent_companies FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_companies_delete_authenticated" ON public.agent_companies;
CREATE POLICY "agent_companies_delete_authenticated"
  ON public.agent_companies FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 4. agent_jobs — listings + initiative applications (single queue; no agent_queue)
-- Status (v2):
--   new → needs_manual_review | reviewing → changes_requested → approved
--       → sending (email undo window) → sent | rejected
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'listing'
    CHECK (kind IN ('listing', 'initiative')),
  company_id uuid REFERENCES public.agent_companies(id) ON DELETE SET NULL,
  apply_method text
    CHECK (apply_method IS NULL OR apply_method IN ('email', 'portal')),
  status text NOT NULL DEFAULT 'new'
    CHECK (status IN (
      'new',
      'needs_manual_review',
      'reviewing',
      'changes_requested',
      'approved',
      'sending',
      'sent',
      'rejected'
    )),
  title text,
  location text,
  language text,
  description text,
  url text,
  source text,
  posted_at date,
  raw_listing_text text,
  relevance jsonb NOT NULL DEFAULT '{}'::jsonb,
  reject_reason text,
  -- Email / initiative: Gmail message id after undo window closes
  gmail_message_id text,
  email_to text,
  -- When status entered 'sending' (30s undo for email)
  sending_started_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_user_id
  ON public.agent_jobs (user_id);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_user_status
  ON public.agent_jobs (user_id, status);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_company_id
  ON public.agent_jobs (company_id);

ALTER TABLE public.agent_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_jobs_select_authenticated" ON public.agent_jobs;
DROP POLICY IF EXISTS "agent_jobs_insert_authenticated" ON public.agent_jobs;
DROP POLICY IF EXISTS "agent_jobs_update_authenticated" ON public.agent_jobs;
DROP POLICY IF EXISTS "agent_jobs_delete_authenticated" ON public.agent_jobs;

DROP POLICY IF EXISTS "agent_jobs_select_authenticated" ON public.agent_jobs;
CREATE POLICY "agent_jobs_select_authenticated"
  ON public.agent_jobs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_jobs_insert_authenticated" ON public.agent_jobs;
CREATE POLICY "agent_jobs_insert_authenticated"
  ON public.agent_jobs FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_jobs_update_authenticated" ON public.agent_jobs;
CREATE POLICY "agent_jobs_update_authenticated"
  ON public.agent_jobs FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_jobs_delete_authenticated" ON public.agent_jobs;
CREATE POLICY "agent_jobs_delete_authenticated"
  ON public.agent_jobs FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 5. agent_drafts — tailored CV/cover + cited facts snapshot at draft time
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.agent_jobs(id) ON DELETE CASCADE,
  cv_text text,
  cover_text text,
  -- Snapshot of cited facts ({id, text}…) for traceability after edit/delete
  cited_facts_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  fabrication_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_drafts_user_id
  ON public.agent_drafts (user_id);

CREATE INDEX IF NOT EXISTS idx_agent_drafts_job_id
  ON public.agent_drafts (job_id);

ALTER TABLE public.agent_drafts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_drafts_select_authenticated" ON public.agent_drafts;
DROP POLICY IF EXISTS "agent_drafts_insert_authenticated" ON public.agent_drafts;
DROP POLICY IF EXISTS "agent_drafts_update_authenticated" ON public.agent_drafts;
DROP POLICY IF EXISTS "agent_drafts_delete_authenticated" ON public.agent_drafts;

DROP POLICY IF EXISTS "agent_drafts_select_authenticated" ON public.agent_drafts;
CREATE POLICY "agent_drafts_select_authenticated"
  ON public.agent_drafts FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_drafts_insert_authenticated" ON public.agent_drafts;
CREATE POLICY "agent_drafts_insert_authenticated"
  ON public.agent_drafts FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_drafts_update_authenticated" ON public.agent_drafts;
CREATE POLICY "agent_drafts_update_authenticated"
  ON public.agent_drafts FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_drafts_delete_authenticated" ON public.agent_drafts;
CREATE POLICY "agent_drafts_delete_authenticated"
  ON public.agent_drafts FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 6. agent_activity — run logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_activity (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  run_at timestamptz NOT NULL DEFAULT now(),
  kind text NOT NULL DEFAULT 'run',
  fetched integer NOT NULL DEFAULT 0,
  relevant integer NOT NULL DEFAULT 0,
  drafted integer NOT NULL DEFAULT 0,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_activity_user_id
  ON public.agent_activity (user_id);

CREATE INDEX IF NOT EXISTS idx_agent_activity_run_at
  ON public.agent_activity (user_id, run_at DESC);

ALTER TABLE public.agent_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_activity_select_authenticated" ON public.agent_activity;
DROP POLICY IF EXISTS "agent_activity_insert_authenticated" ON public.agent_activity;
DROP POLICY IF EXISTS "agent_activity_update_authenticated" ON public.agent_activity;
DROP POLICY IF EXISTS "agent_activity_delete_authenticated" ON public.agent_activity;

DROP POLICY IF EXISTS "agent_activity_select_authenticated" ON public.agent_activity;
CREATE POLICY "agent_activity_select_authenticated"
  ON public.agent_activity FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_activity_insert_authenticated" ON public.agent_activity;
CREATE POLICY "agent_activity_insert_authenticated"
  ON public.agent_activity FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_activity_update_authenticated" ON public.agent_activity;
CREATE POLICY "agent_activity_update_authenticated"
  ON public.agent_activity FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_activity_delete_authenticated" ON public.agent_activity;
CREATE POLICY "agent_activity_delete_authenticated"
  ON public.agent_activity FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

NOTIFY pgrst, 'reload schema';


-- ========== 021_agent_jobs_source_key.sql ==========

-- Job agents v2 — Phase 3 additive: stable source key for listing upsert/dedupe
-- Pair: 021_agent_jobs_source_key_down.sql

ALTER TABLE public.agent_jobs
  ADD COLUMN IF NOT EXISTS source_key text;

COMMENT ON COLUMN public.agent_jobs.source_key IS
  'Stable idempotency key: {source}:{externalId}. NULL for initiative / manual rows.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_jobs_user_source_key
  ON public.agent_jobs (user_id, source_key)
  WHERE source_key IS NOT NULL;

NOTIFY pgrst, 'reload schema';


-- ========== 022_agent_jobs_not_relevant_status.sql ==========

-- Job agents v2 — Phase 4: allow not_relevant after Claude fit review
-- Pair: 022_agent_jobs_not_relevant_status_down.sql
--
-- Documented status choice (Phase 4):
--   new + relevant=true  → reviewing
--   new + relevant=false → not_relevant (stored explanation; NOT auto-rejected / not sent)
--   new + invalid JSON after retry → needs_manual_review

ALTER TABLE public.agent_jobs DROP CONSTRAINT IF EXISTS agent_jobs_status_check;

ALTER TABLE public.agent_jobs
  ADD CONSTRAINT agent_jobs_status_check
  CHECK (status IN (
    'new',
    'needs_manual_review',
    'reviewing',
    'not_relevant',
    'changes_requested',
    'approved',
    'sending',
    'sent',
    'rejected'
  ));

COMMENT ON COLUMN public.agent_jobs.relevance IS
  'Phase 4 Claude fit JSON: {relevant, requirements_met[{requirement, evidence_fact_ids}], requirements_not_met, summary, listing_language}. No scores.';

COMMENT ON COLUMN public.agent_jobs.status IS
  'v2: new → needs_manual_review | reviewing | not_relevant → changes_requested → approved → sending → sent | rejected';

NOTIFY pgrst, 'reload schema';


-- ========== 023_agent_controls_scheduling.sql ==========

-- Job agents Phase 9 — per-agent pause controls + company scout watchlist
-- Additive. Pair: 023_agent_controls_scheduling_down.sql

-- ---------------------------------------------------------------------------
-- 1. agent_agent_controls — pause / resume per agent kind
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agent_agent_controls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  agent_key text NOT NULL
    CHECK (agent_key IN ('job_scout', 'company_scout', 'assessor', 'writer')),
  paused boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT agent_agent_controls_user_key_unique UNIQUE (user_id, agent_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_agent_controls_user_id
  ON public.agent_agent_controls (user_id);

ALTER TABLE public.agent_agent_controls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_agent_controls_select_authenticated" ON public.agent_agent_controls;
DROP POLICY IF EXISTS "agent_agent_controls_insert_authenticated" ON public.agent_agent_controls;
DROP POLICY IF EXISTS "agent_agent_controls_update_authenticated" ON public.agent_agent_controls;
DROP POLICY IF EXISTS "agent_agent_controls_delete_authenticated" ON public.agent_agent_controls;

DROP POLICY IF EXISTS "agent_agent_controls_select_authenticated" ON public.agent_agent_controls;
CREATE POLICY "agent_agent_controls_select_authenticated"
  ON public.agent_agent_controls FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_agent_controls_insert_authenticated" ON public.agent_agent_controls;
CREATE POLICY "agent_agent_controls_insert_authenticated"
  ON public.agent_agent_controls FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_agent_controls_update_authenticated" ON public.agent_agent_controls;
CREATE POLICY "agent_agent_controls_update_authenticated"
  ON public.agent_agent_controls FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "agent_agent_controls_delete_authenticated" ON public.agent_agent_controls;
CREATE POLICY "agent_agent_controls_delete_authenticated"
  ON public.agent_agent_controls FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 2. Company Scout watchlist on search settings
-- ---------------------------------------------------------------------------
ALTER TABLE public.agent_search_settings
  ADD COLUMN IF NOT EXISTS target_companies text[] NOT NULL DEFAULT '{}'::text[];

NOTIFY pgrst, 'reload schema';

